import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "AI Travel Planner",
  description: "Generated by AI Travel Planner",

  icons: {
    icon: "/globe.svg",
  },

  openGraph: {
    title: "AI Travel Planner",
    description: "Generated by AI Travel Planner",
    images: [
      {
        url: "/globe.png",
        width: 1200,
        height: 630,
        alt: "AI Travel Planner",
      },
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}
        <Toaster position="top-right" />
      </body>
    </html>
  );
}
